### PR TITLE
Highlighted Code is Implemented

### PR DESCRIPTION
**Pull request by EdOates84**
### Implementation

Code: Several Generate code currently a neural architecture

- [X] Code is Highlighted

- [X] Implement for python

- [ ] implement for other languages bindings 

### Screenshot

Screenshot from 2020-02-01 03-49-36

### CODE REVIEW

**Comment by orionpax00** [comment]
Hi @EdOates84,
It looks nice but I think the color schema is not applied properly, it should looks something like this:
firefox_5q0fBywhJQ
or in any other theme.

And also fix merge conflict and also remove committed node_modules folder :)

**Comment by EdOates84** [comment]
Ok i'll fix it asap

**Comment by EdOates84** [comment]
Hey @orionpax00 ,
I've tried so many times with the different libraries but the final output is the same from all the libraries.
Kindly have a look


1. react-highlight-

Screenshot from 2020-02-03 06-34-32

2. react-syntax-highlighter-

Screenshot from 2020-02-03 16-09-05

**Comment by ivantha** [comment]
Closing as stale.

**Pull request closed without merging**
