### PR TITLE
Data preprocessing stage.

### PR DESCRIPTION
**Pull request by bruce-wayne99**
### Functionalities.
- Added functionality for editing dataset names with UI. (screenshots below)
image
image

- Added functionality for deleting dataset entries.
- Below gif including both editing and deleting datasets.
gsoc_1

### CODE REVIEW

**Comment by bruce-wayne99** [comment]
### Pagination
- Pagination has been implemented for displaying datasets.
gsoc_2
- The above is a gif displaying it, more styling can be added to make it look good.

**Comment by ivantha** [comment]
@bruce-wayne99 Please rebase properly.

**Comment by bruce-wayne99** [comment]
@ivantha can you elaborate on the issue?, the branch `data-preproc` is upto date with the `master` branch of scorelab tensormap.

**Comment by ivantha** [comment]
> @ivantha can you elaborate on the issue?, the branch `data-preproc` is upto date with the `master` branch of scorelab tensormap.

It is not. Please rebase the PR properly. @sumedhe will help you.

**Pull request closed without merging**
