### PR TITLE
Fixed Bugs in View and Visualize data

### PR DESCRIPTION
**Pull request by srivastava9**
Bugs in View and visualize data:
[1] the name of file was not visible.(also in issue #99  )
Screenshot from 2020-02-26 13-29-30
[2] clicking the visualize would show an error (also in issue #101 )
For this i have to also change backend api to get data.

In data_preprocessing.py changed api of visualize data to this:
Screenshot from 2020-02-27 00-57-51

Screenshot from 2020-02-26 13-29-53

[3] Clicking on one dataset to delete would auto select all due to undefined id.
ezgif com-video-to-gif
Fixed this to select for delete each alone.
Screenshot from 2020-02-26 13-29-30

[4] changed xmlhttprequest in viewdata.js to make fetch and made it asynchronous by updating the component in table when new props is passed. Making opening of viewdata fast.
Screenshot from 2020-02-27 01-02-35
Screenshot from 2020-02-27 01-02-45

### CODE REVIEW

**Comment by srivastava9** [comment]
@orionpax00 @ivantha @suleka96 @sumedhe  Please Do Review this :)

**Comment by AdityaSrivast** [comment]
@srivastava9 I already have 2 PRs pending for the same issues you have mentioned. For the changes regarding fetch api, I have already raised an issue asking for suggestions. So you can delete this PR. This is no way of working on Open source projects.

**Comment by srivastava9** [comment]
Hey @AdityaSrivast your pr for visualise data would not be able to fetch data from backend due to api changes. I accept you made a pr for filename showing but as i was solving all these bugs i do not saw your pr.

**Comment by AdityaSrivast** [comment]
@srivastava9 If you felt my PR had some issues, you should comment on my PR, and not make another PR of your own. 
Also I have already mentioned in all my issues that I am already working on them. You cannot take up any issue just like that.

**Comment by ivantha** [comment]
Closing as stale.

**Pull request closed without merging**
