### PR TITLE
Basic drag and drop UI

### PR DESCRIPTION
**Pull request by orionpax00**
I have create a basic Drag and Drop frontend component, the functionality is implemented using [react-diagrams](https://github.com/projectstorm/react-diagrams/)

### CODE REVIEW

**Comment by ivantha** [comment]
@orionpax00 Can you please include some screenshots of your new changes?

**Comment by orionpax00** [comment]
Hi @ivantha,
Please find the screenshots related to need changes

1. **Home Screen**
Screenshot (18)

 
2. **Changed Screen (a)**
Screenshot (17)

**Comment by ivantha** [comment]
### Conventions
image
- ^ Please rebase the branch properly. And next time you can work on a different branch of this (original) repository. 
- Stick to basic Git commit conventions such as
  - Start with a capital letter
  - Use the imperative mood in the subject line
- Include screenshots in the description of the PR. 

### Implementation
- The user should be able to freely move the components in the workspace.

**Comment by orionpax00** [comment]
@ivantha,
I'll create a new pull request,
Sorry for trouble.

**Comment by ivantha** [comment]
@orionpax00 Thats totally alright 🙂

**Pull request closed without merging**
