### PR TITLE
Changes in ui and made validation for weight and activation for link parameters

### PR DESCRIPTION
**Pull request by srivastava9**
Screenshot from 2020-02-20 19-19-36

### CODE REVIEW

**Comment by orionpax00** [comment]
@srivastava9 it seems that there is an inappropriate spacing between icon and text in the sidebar, try to fix that :)

**Comment by srivastava9** [comment]
@orionpax00 I removed the spaces
Screenshot from 2020-02-22 18-08-21
Do have a look :)

**Comment by orionpax00** [comment]
LGTM :)

**Comment by srivastava9** [comment]
@orionpax00 Thanks Sir,COuld You please merge this. :)

**Pull request merged**
