### PR TITLE
Logo

### PR DESCRIPTION
**Pull request by kunalbhatia18**

### CODE REVIEW

**Comment by alpha2320** [comment]
t

here is my design !

**Comment by alpha2320** [comment]
TENSOR MAP

HERE IS NEW DESIGN

**Comment by SufiyanPasta** [comment]
logo

@kunalbhatia18 @alpha2320 Love both of your logo here is mine

**Comment by alpha2320** [comment]
Nice man! Srsly u have put in a lot of work congrats!. Keep it up.

**Comment by sharman13** [comment]
@alpha2320 how many tasks you have completed?

**Comment by sharman13** [comment]
My logo
tensormap logo

**Comment by ivantha** [comment]
Closing as stale.

**Pull request closed without merging**
